/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 20:16:08 GMT 2025
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert ÜNİ<|start_header_id|><|start_header_id|><|start_header_id|>assistant<|end_header_id|>

`