/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Jun 21 21:22:52 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.loa.service;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class LoaLoanService_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanService"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Repos\\EvoGen\\TheEvoGen"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\cbark\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(LoaLoanService_ESTest_scaffolding.class.getClassLoader() ,
      "com.cbarkinozer.onlinebankingrestapi.app.loa.dto.LoaPayLoanOffResponseDto",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService",
      "com.cbarkinozer.onlinebankingrestapi.app.gen.exceptions.IllegalFieldException",
      "com.cbarkinozer.onlinebankingrestapi.app.gen.exceptions.GenBusinessException",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.service.entityservice.LoaLoanPaymentEntityService",
      "com.cbarkinozer.onlinebankingrestapi.app.gen.service.BaseEntityService",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.dto.LoaCalculateLateFeeResponseDto",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.entity.LoaLoanPayment",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.dto.LoaPayInstallmentResponseDto",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.enums.LoaErrorMessage",
      "com.cbarkinozer.onlinebankingrestapi.app.gen.entity.BaseModel",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanService",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.service.entityservice.LoaLoanEntityService",
      "com.cbarkinozer.onlinebankingrestapi.app.gen.exceptions.ItemNotFoundException",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.dto.LoaLoanDto",
      "com.cbarkinozer.onlinebankingrestapi.app.cus.service.entityservice.CusCustomerEntityService",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.entity.LoaLoan",
      "com.cbarkinozer.onlinebankingrestapi.app.gen.entity.BaseEntity",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.dto.LoaApplyLoanDto",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.dto.LoaCalculateLoanResponseDto",
      "com.cbarkinozer.onlinebankingrestapi.app.gen.enums.BaseErrorMessage"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(LoaLoanService_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanService",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.enums.LoaLoanStatusType",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.mapper.LoaLoanMapper",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService",
      "com.cbarkinozer.onlinebankingrestapi.app.gen.exceptions.GenBusinessException",
      "com.cbarkinozer.onlinebankingrestapi.app.gen.exceptions.IllegalFieldException",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.enums.LoaErrorMessage",
      "com.cbarkinozer.onlinebankingrestapi.app.gen.entity.BaseEntity",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.entity.LoaLoanPayment",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.dto.LoaApplyLoanDto",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.entity.LoaLoan",
      "com.cbarkinozer.onlinebankingrestapi.app.gen.entity.BaseAdditionalFields",
      "com.cbarkinozer.onlinebankingrestapi.app.loa.dto.LoaCalculateLoanResponseDto"
    );
  }
}
