/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 21:23:04 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.loa.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cbarkinozer.onlinebankingrestapi.app.cus.service.entityservice.CusCustomerEntityService;
import com.cbarkinozer.onlinebankingrestapi.app.loa.dto.LoaApplyLoanDto;
import com.cbarkinozer.onlinebankingrestapi.app.loa.entity.LoaLoan;
import com.cbarkinozer.onlinebankingrestapi.app.loa.enums.LoaLoanStatusType;
import com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService;
import java.math.BigDecimal;
import java.time.Clock;
import java.time.Duration;
import java.time.LocalDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LoaLoanValidationService_ESTest extends LoaLoanValidationService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      loaLoanValidationService0.controlIsInstallmentCountNotGreaterThanInstallmentCountLimit(0, 481);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      loaLoanValidationService0.controlIsTaxRateNotNegative(bigDecimal0);
      assertEquals((short)10, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      loaLoanValidationService0.controlIsRemainingPrincipalNotNegative(bigDecimal0);
      assertEquals((short)0, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      Clock clock0 = MockClock.systemDefaultZone();
      Duration duration0 = Duration.ofMinutes((-2039L));
      Clock clock1 = MockClock.offset(clock0, duration0);
      LocalDate localDate0 = MockLocalDate.now(clock1);
      Long long0 = loaLoanValidationService0.controlIsLoanDueDatePast(localDate0);
      assertEquals(1L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsPrincipalLoanAmountPositive(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      loaLoanValidationService0.controlIsInterestAmountNotNegative(bigDecimal0);
      assertEquals((byte)10, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((long) (-1880));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsMonthlyInstallmentAmountPositive(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      BigDecimal bigDecimal1 = new BigDecimal(569L);
      loaLoanValidationService0.controlIsLoanAmountNotGreaterThanMaxLoanAmount(bigDecimal0, bigDecimal1);
      assertFalse(bigDecimal0.equals((Object)bigDecimal1));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      loaLoanValidationService0.controlIsLateInterestTaxNotNegative(bigDecimal0);
      assertEquals((short)0, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsTotalLateFeePositive(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      loaLoanValidationService0.controlIsLateFeeRateNotNegative(bigDecimal0);
      assertEquals((short)0, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-1.0));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsTotalPaymentPositive(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.valueOf((double) 1987L);
      BigDecimal bigDecimal1 = bigDecimal0.negate();
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsInstallmentAmountPositive(bigDecimal1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      loaLoanValidationService0.controlIsInterestRateNotNegative(bigDecimal0);
      assertEquals((byte)0, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsTotalPaymentPositive((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsTotalLateFeePositive((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsTaxRateNotNegative((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsRemainingPrincipalNotNegative((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsPrincipalLoanAmountPositive((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsParameterNotNull((LoaApplyLoanDto) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsMonthlyInstallmentAmountPositive((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsLoanNotAlreadyPaidOff((LoaLoan) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsLoanDueDatePast((LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.time.temporal.ChronoUnit", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsLoanAmountNotGreaterThanMaxLoanAmount((BigDecimal) null, (BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsLateInterestTaxNotNegative((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsLateFeeRateNotNegative((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsInterestRateNotNegative((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsInterestAmountNotNegative((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsInstallmentAmountPositive((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsCustomerExist((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsLoanDueDatePast(localDate0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      LoaLoan loaLoan0 = new LoaLoan();
      LoaLoanStatusType loaLoanStatusType0 = LoaLoanStatusType.PAID;
      loaLoan0.setLoanStatusType(loaLoanStatusType0);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsLoanNotAlreadyPaidOff(loaLoan0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      LoaLoan loaLoan0 = new LoaLoan();
      loaLoanValidationService0.controlIsLoanNotAlreadyPaidOff(loaLoan0);
      assertNull(loaLoan0.getId());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsInstallmentCountNotGreaterThanInstallmentCountLimit(0, (-106));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      loaLoanValidationService0.controlIsInstallmentCountNotGreaterThanInstallmentCountLimit((-755), (-755));
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-4147));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsTaxRateNotNegative(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      loaLoanValidationService0.controlIsTaxRateNotNegative(bigDecimal0);
      assertEquals((byte)0, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-1));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsRemainingPrincipalNotNegative(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      loaLoanValidationService0.controlIsRemainingPrincipalNotNegative(bigDecimal0);
      assertEquals((byte)10, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-927L));
      Long long0 = loaLoanValidationService0.controlIsLoanDueDatePast(localDate0);
      assertEquals(17042L, (long)long0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-3433));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsPrincipalLoanAmountPositive(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      loaLoanValidationService0.controlIsPrincipalLoanAmountPositive(bigDecimal0);
      assertEquals((short)1, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-662));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsInterestAmountNotNegative(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      loaLoanValidationService0.controlIsInterestAmountNotNegative(bigDecimal0);
      assertEquals((byte)0, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsMonthlyInstallmentAmountPositive(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      loaLoanValidationService0.controlIsMonthlyInstallmentAmountPositive(bigDecimal0);
      assertEquals((short)1, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      BigDecimal bigDecimal1 = new BigDecimal((-970L));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsLoanAmountNotGreaterThanMaxLoanAmount(bigDecimal0, bigDecimal1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      loaLoanValidationService0.controlIsLoanAmountNotGreaterThanMaxLoanAmount(bigDecimal0, bigDecimal0);
      assertEquals((byte)1, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-1.0));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsLateInterestTaxNotNegative(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      loaLoanValidationService0.controlIsLateInterestTaxNotNegative(bigDecimal0);
      assertEquals((byte)1, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-1386.644025));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsTotalLateFeePositive(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      loaLoanValidationService0.controlIsTotalLateFeePositive(bigDecimal0);
      assertEquals((byte)10, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-1L));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsLateFeeRateNotNegative(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      loaLoanValidationService0.controlIsLateFeeRateNotNegative(bigDecimal0);
      assertEquals((short)1, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal(0.0);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsTotalPaymentPositive(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      loaLoanValidationService0.controlIsTotalPaymentPositive(bigDecimal0);
      assertEquals((short)10, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsInstallmentAmountPositive(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      loaLoanValidationService0.controlIsInstallmentAmountPositive(bigDecimal0);
      assertEquals((byte)10, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-1431655764));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsInterestRateNotNegative(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.valueOf(1566L);
      loaLoanValidationService0.controlIsInterestRateNotNegative(bigDecimal0);
      assertEquals((byte)30, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      Integer integer0 = new Integer(1890);
      LoaApplyLoanDto loaApplyLoanDto0 = new LoaApplyLoanDto();
      loaApplyLoanDto0.setPrincipalLoanAmount(bigDecimal0);
      loaApplyLoanDto0.setMonthlySalary(bigDecimal0);
      loaApplyLoanDto0.setInstallmentCount(integer0);
      loaLoanValidationService0.controlIsParameterNotNull(loaApplyLoanDto0);
      assertEquals("LoaApplyLoanDto(installmentCount=1890, principalLoanAmount=0, monthlySalary=0)", loaApplyLoanDto0.toString());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      LoaApplyLoanDto loaApplyLoanDto0 = new LoaApplyLoanDto();
      BigDecimal bigDecimal0 = new BigDecimal(0.0);
      Integer integer0 = Integer.valueOf(2147480704);
      loaApplyLoanDto0.setInstallmentCount(integer0);
      loaApplyLoanDto0.setPrincipalLoanAmount(bigDecimal0);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsParameterNotNull(loaApplyLoanDto0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      LoaApplyLoanDto loaApplyLoanDto0 = new LoaApplyLoanDto();
      Integer integer0 = Integer.valueOf(2147480704);
      loaApplyLoanDto0.setInstallmentCount(integer0);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsParameterNotNull(loaApplyLoanDto0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      LoaApplyLoanDto loaApplyLoanDto0 = new LoaApplyLoanDto();
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsParameterNotNull(loaApplyLoanDto0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      Integer integer0 = new Integer((-1));
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsParameterNotNull(integer0, (BigDecimal) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      Integer integer0 = new Integer((-1));
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      loaLoanValidationService0.controlIsParameterNotNull(integer0, bigDecimal0);
      assertEquals((short)0, bigDecimal0.shortValue());
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      LoaLoanValidationService loaLoanValidationService0 = new LoaLoanValidationService((CusCustomerEntityService) null);
      // Undeclared exception!
      try { 
        loaLoanValidationService0.controlIsParameterNotNull((Integer) null, (BigDecimal) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.loa.service.LoaLoanValidationService", e);
      }
  }
}
