/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 21:05:43 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.acc.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cbarkinozer.onlinebankingrestapi.app.acc.dto.AccMoneyActivityDto;
import com.cbarkinozer.onlinebankingrestapi.app.acc.enums.AccAccountActivityType;
import java.math.BigDecimal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AccMoneyActivityDto$AccMoneyActivityDtoBuilder_ESTest extends AccMoneyActivityDto$AccMoneyActivityDtoBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AccMoneyActivityDto.AccMoneyActivityDtoBuilder accMoneyActivityDto_AccMoneyActivityDtoBuilder0 = new AccMoneyActivityDto.AccMoneyActivityDtoBuilder();
      AccMoneyActivityDto.AccMoneyActivityDtoBuilder accMoneyActivityDto_AccMoneyActivityDtoBuilder1 = accMoneyActivityDto_AccMoneyActivityDtoBuilder0.accountId((Long) null);
      assertSame(accMoneyActivityDto_AccMoneyActivityDtoBuilder1, accMoneyActivityDto_AccMoneyActivityDtoBuilder0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AccMoneyActivityDto.AccMoneyActivityDtoBuilder accMoneyActivityDto_AccMoneyActivityDtoBuilder0 = new AccMoneyActivityDto.AccMoneyActivityDtoBuilder();
      AccMoneyActivityDto accMoneyActivityDto0 = accMoneyActivityDto_AccMoneyActivityDtoBuilder0.build();
      assertNull(accMoneyActivityDto0.getAccountId());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AccMoneyActivityDto.AccMoneyActivityDtoBuilder accMoneyActivityDto_AccMoneyActivityDtoBuilder0 = new AccMoneyActivityDto.AccMoneyActivityDtoBuilder();
      String string0 = accMoneyActivityDto_AccMoneyActivityDtoBuilder0.toString();
      assertEquals("AccMoneyActivityDto.AccMoneyActivityDtoBuilder(accountId=null, amount=null, activityType=null)", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AccMoneyActivityDto.AccMoneyActivityDtoBuilder accMoneyActivityDto_AccMoneyActivityDtoBuilder0 = new AccMoneyActivityDto.AccMoneyActivityDtoBuilder();
      AccAccountActivityType accAccountActivityType0 = AccAccountActivityType.GET;
      AccMoneyActivityDto.AccMoneyActivityDtoBuilder accMoneyActivityDto_AccMoneyActivityDtoBuilder1 = accMoneyActivityDto_AccMoneyActivityDtoBuilder0.activityType(accAccountActivityType0);
      assertEquals("AccMoneyActivityDto.AccMoneyActivityDtoBuilder(accountId=null, amount=null, activityType=GET)", accMoneyActivityDto_AccMoneyActivityDtoBuilder1.toString());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AccMoneyActivityDto.AccMoneyActivityDtoBuilder accMoneyActivityDto_AccMoneyActivityDtoBuilder0 = new AccMoneyActivityDto.AccMoneyActivityDtoBuilder();
      AccMoneyActivityDto.AccMoneyActivityDtoBuilder accMoneyActivityDto_AccMoneyActivityDtoBuilder1 = accMoneyActivityDto_AccMoneyActivityDtoBuilder0.amount((BigDecimal) null);
      assertSame(accMoneyActivityDto_AccMoneyActivityDtoBuilder1, accMoneyActivityDto_AccMoneyActivityDtoBuilder0);
  }
}
