/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 21:09:09 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.acc.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cbarkinozer.onlinebankingrestapi.app.acc.dto.AccAccountSaveDto;
import com.cbarkinozer.onlinebankingrestapi.app.acc.service.AccAccountService;
import com.cbarkinozer.onlinebankingrestapi.app.acc.service.AccAccountValidationService;
import com.cbarkinozer.onlinebankingrestapi.app.acc.service.entityservice.AccAccountEntityService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AccAccountService_ESTest extends AccAccountService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AccAccountService accAccountService0 = new AccAccountService((AccAccountEntityService) null, (AccAccountValidationService) null);
      // Undeclared exception!
      try { 
        accAccountService0.findAllAccounts();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.acc.service.AccAccountService", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AccAccountService accAccountService0 = new AccAccountService((AccAccountEntityService) null, (AccAccountValidationService) null);
      // Undeclared exception!
      try { 
        accAccountService0.findAccountByCustomerId((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.acc.service.AccAccountService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AccAccountService accAccountService0 = new AccAccountService((AccAccountEntityService) null, (AccAccountValidationService) null);
      AccAccountSaveDto accAccountSaveDto0 = new AccAccountSaveDto();
      // Undeclared exception!
      try { 
        accAccountService0.saveAccount(accAccountSaveDto0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/lang3/RandomStringUtils
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.gen.util.StringUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AccAccountService accAccountService0 = new AccAccountService((AccAccountEntityService) null, (AccAccountValidationService) null);
      // Undeclared exception!
      try { 
        accAccountService0.findAccountById((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.acc.service.AccAccountService", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AccAccountService accAccountService0 = new AccAccountService((AccAccountEntityService) null, (AccAccountValidationService) null);
      // Undeclared exception!
      try { 
        accAccountService0.cancelAccount((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.acc.service.AccAccountService", e);
      }
  }
}
