/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 21:18:30 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.kafka.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cbarkinozer.onlinebankingrestapi.app.kafka.dto.LogMessage;
import java.time.LocalDateTime;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LogMessage$LogMessageBuilder_ESTest extends LogMessage$LogMessageBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LogMessage.LogMessageBuilder logMessage_LogMessageBuilder0 = new LogMessage.LogMessageBuilder();
      Long long0 = new Long(0L);
      LogMessage.LogMessageBuilder logMessage_LogMessageBuilder1 = logMessage_LogMessageBuilder0.id(long0);
      assertSame(logMessage_LogMessageBuilder0, logMessage_LogMessageBuilder1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LogMessage.LogMessageBuilder logMessage_LogMessageBuilder0 = new LogMessage.LogMessageBuilder();
      String string0 = logMessage_LogMessageBuilder0.toString();
      assertEquals("LogMessage.LogMessageBuilder(id=null, message=null, description=null, dateTime=null)", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LogMessage.LogMessageBuilder logMessage_LogMessageBuilder0 = new LogMessage.LogMessageBuilder();
      LogMessage logMessage0 = logMessage_LogMessageBuilder0.build();
      assertNull(logMessage0.getId());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LogMessage.LogMessageBuilder logMessage_LogMessageBuilder0 = new LogMessage.LogMessageBuilder();
      LogMessage.LogMessageBuilder logMessage_LogMessageBuilder1 = logMessage_LogMessageBuilder0.description("t:h^'Ev5");
      assertEquals("LogMessage.LogMessageBuilder(id=null, message=null, description=t:h^'Ev5, dateTime=null)", logMessage_LogMessageBuilder1.toString());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LogMessage.LogMessageBuilder logMessage_LogMessageBuilder0 = new LogMessage.LogMessageBuilder();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LogMessage.LogMessageBuilder logMessage_LogMessageBuilder1 = logMessage_LogMessageBuilder0.dateTime(localDateTime0);
      assertSame(logMessage_LogMessageBuilder0, logMessage_LogMessageBuilder1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LogMessage.LogMessageBuilder logMessage_LogMessageBuilder0 = new LogMessage.LogMessageBuilder();
      LogMessage.LogMessageBuilder logMessage_LogMessageBuilder1 = logMessage_LogMessageBuilder0.message((String) null);
      assertSame(logMessage_LogMessageBuilder1, logMessage_LogMessageBuilder0);
  }
}
