/*
 * This file was automatically generated by EvoSuite
 * Sat Jun21 21:18:24 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.kafka.consumer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cbarkinozer.onlinebankingrestapi.app.kafka.dto.LogMessage;
import com.cbarkinozer.onlinebankingrestapi.app.log.service.entityservice.LogDetailEntityService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) 
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class KafkaListenerService_ESTest extends KafkaListenerService_ESTest_scaffolding {

    /**
     * Test that listen() method throws NullPointerException when given a null LogMessage.
     */
    @Test(timeout = 4000)
    public void testListen_WithNullLogMessage_ThrowsNullPointerException() throws Throwable {
        KafkaListenerService kafkaListenerService = new KafkaListenerService((LogDetailEntityService) null);
        try { 
            kafkaListenerService.listen((LogMessage) null);
            fail("Expecting exception: NullPointerException");
        } catch(NullPointerException e) {
            verifyException("com.cbarkinozer.onlinebankingrestapi.app.kafka.consumer.KafkaListenerService", e);
        }
    }

    /**
     * Test that saveLogToDb() method throws NoClassDefFoundError when given a null LogMessage.
     */
    @Test(timeout = 4000)
    public void testSaveLogToDb_WithNullLogMessage_ThrowsNoClassDefFoundError() throws Throwable {
        KafkaListenerService kafkaListenerService = new KafkaListenerService((LogDetailEntityService) null);
        try { 
            kafkaListenerService.saveLogToDb((LogMessage) null);
            fail("Expecting exception: NoClassDefFoundError");
        } catch(NoClassDefFoundError e) {
            verifyException("com.cbarkinozer.onlinebankingrestapi.app.kafka.consumer.KafkaListenerService", e);
        }
    }

    /**
     * Test that listen() method throws NoClassDefFoundError when given a valid LogMessage.
     */
    @Test(timeout = 4000)
    public void testListen_WithValidLogMessage_ThrowsNoClassDefFoundError() throws Throwable {
        KafkaListenerService kafkaListenerService = new KafkaListenerService((LogDetailEntityService) null);
        LogMessage logMessage = new LogMessage();
        try { 
            kafkaListenerService.listen(logMessage);
            fail("Expecting exception: NoClassDefFoundError");
        } catch(NoClassDefFoundError e) {
            verifyException("com.cbarkinozer.onlinebankingrestapi.app.kafka.consumer.KafkaListenerService", e);
        }
    }
}