/*
 * This file was automatically generated by EvoSuite
 * Sat Jun21 21:19:27 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.kafka.producer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cbarkinozer.onlinebankingrestapi.app.kafka.dto.LogMessage;
import com.cbarkinozer.onlinebankingrestapi.app.log.service.LogService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) 
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class KafkaMessageController_ESTest extends KafkaMessageController_ESTest_scaffolding {

    /**
     * Test the sendMessage method with a null LogService to verify it throws a NullPointerException.
     */
    @Test(timeout = 4000)
    public void testSendMessage_WithNullLogService_ShouldThrowNullPointerException() throws Throwable {
        KafkaMessageController kafkaMessageController = new KafkaMessageController((LogService) null);
        LogMessage logMessage = new LogMessage();
        // Undeclared exception!
        try { 
            kafkaMessageController.sendMessage(logMessage);
            fail("Expecting exception: NullPointerException");
        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("com.cbarkinozer.onlinebankingrestapi.app.kafka.producer.KafkaMessageController", e);
        }
    }
}