/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 21:14:31 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.crd.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cbarkinozer.onlinebankingrestapi.app.crd.dto.CrdCreditCardPaymentDto;
import com.cbarkinozer.onlinebankingrestapi.app.crd.dto.CrdCreditCardSaveDto;
import com.cbarkinozer.onlinebankingrestapi.app.crd.dto.CrdCreditCardSpendDto;
import com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardService;
import com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService;
import com.cbarkinozer.onlinebankingrestapi.app.crd.service.entityservice.CrdCreditCardActivityEntityService;
import com.cbarkinozer.onlinebankingrestapi.app.crd.service.entityservice.CrdCreditCardEntityService;
import java.math.BigDecimal;
import java.time.LocalDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CrdCreditCardService_ESTest extends CrdCreditCardService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, crdCreditCardValidationService0, (CrdCreditCardActivityEntityService) null);
      Long long0 = new Long(1164L);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(2574L);
      // Undeclared exception!
      try { 
        crdCreditCardService0.findCreditCardActivityBetweenDates(long0, localDate0, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardService", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, crdCreditCardValidationService0, (CrdCreditCardActivityEntityService) null);
      CrdCreditCardPaymentDto crdCreditCardPaymentDto0 = new CrdCreditCardPaymentDto();
      BigDecimal bigDecimal0 = new BigDecimal((-5510));
      Long long0 = new Long((-5510));
      crdCreditCardPaymentDto0.setCrdCreditCardId(long0);
      crdCreditCardPaymentDto0.setAmount(bigDecimal0);
      // Undeclared exception!
      try { 
        crdCreditCardService0.receivePayment(crdCreditCardPaymentDto0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardService", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, crdCreditCardValidationService0, (CrdCreditCardActivityEntityService) null);
      Long long0 = new Long(2574L);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(2574L);
      // Undeclared exception!
      try { 
        crdCreditCardService0.findCreditCardActivityBetweenDates(long0, localDate0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardService", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, (CrdCreditCardValidationService) null, (CrdCreditCardActivityEntityService) null);
      CrdCreditCardSpendDto crdCreditCardSpendDto0 = new CrdCreditCardSpendDto();
      // Undeclared exception!
      try { 
        crdCreditCardService0.spendMoney(crdCreditCardSpendDto0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardService", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, crdCreditCardValidationService0, (CrdCreditCardActivityEntityService) null);
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      // Undeclared exception!
      try { 
        crdCreditCardService0.saveCreditCard(crdCreditCardSaveDto0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, crdCreditCardValidationService0, (CrdCreditCardActivityEntityService) null);
      CrdCreditCardPaymentDto crdCreditCardPaymentDto0 = new CrdCreditCardPaymentDto();
      // Undeclared exception!
      try { 
        crdCreditCardService0.receivePayment(crdCreditCardPaymentDto0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, crdCreditCardValidationService0, (CrdCreditCardActivityEntityService) null);
      CrdCreditCardSpendDto crdCreditCardSpendDto0 = new CrdCreditCardSpendDto();
      // Undeclared exception!
      try { 
        crdCreditCardService0.spendMoney(crdCreditCardSpendDto0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, crdCreditCardValidationService0, (CrdCreditCardActivityEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardService0.refundMoney((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardService", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, crdCreditCardValidationService0, (CrdCreditCardActivityEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardService0.cancelCreditCard((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardService", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      crdCreditCardSaveDto0.setEarning(bigDecimal0);
      Integer integer0 = new Integer(3);
      crdCreditCardSaveDto0.setCutOffDay(integer0);
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, crdCreditCardValidationService0, (CrdCreditCardActivityEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardService0.saveCreditCard(crdCreditCardSaveDto0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardService", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, crdCreditCardValidationService0, (CrdCreditCardActivityEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardService0.findCreditCardById((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardService", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, crdCreditCardValidationService0, (CrdCreditCardActivityEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardService0.getCardDetails((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardService", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CrdCreditCardService crdCreditCardService0 = new CrdCreditCardService((CrdCreditCardEntityService) null, (CrdCreditCardValidationService) null, (CrdCreditCardActivityEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardService0.findAllCreditCards();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardService", e);
      }
  }
}
