/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 21:13:53 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.crd.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.cbarkinozer.onlinebankingrestapi.app.crd.dto.CrdCreditCardSpendDto;
import com.cbarkinozer.onlinebankingrestapi.app.crd.entity.CrdCreditCard;
import com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService;
import com.cbarkinozer.onlinebankingrestapi.app.crd.service.entityservice.CrdCreditCardEntityService;
import com.cbarkinozer.onlinebankingrestapi.app.gen.enums.GenStatusType;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.Clock;
import java.time.LocalDate;
import java.time.ZoneOffset;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CrdCreditCardValidationService_ESTest extends CrdCreditCardValidationService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal(1.0);
      crdCreditCardValidationService0.controlIsEarningNotNegative(bigDecimal0);
      assertEquals((byte)1, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      Integer integer0 = new Integer(31);
      crdCreditCardValidationService0.isCutOffDayValid(integer0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      crdCreditCardValidationService0.validateCardLimit(bigDecimal0);
      assertEquals((byte)0, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.validateCardLimit((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.isCutOffDayValid((Integer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlIsEarningNotNegative((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      GenStatusType genStatusType0 = GenStatusType.PASSIVE;
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlIsCardCancelled(genStatusType0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      GenStatusType genStatusType0 = GenStatusType.ACTIVE;
      crdCreditCardValidationService0.controlIsCardCancelled(genStatusType0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      Clock clock0 = Clock.tickMillis(zoneOffset0);
      LocalDate localDate0 = MockLocalDate.now(clock0);
      CrdCreditCardSpendDto crdCreditCardSpendDto0 = new CrdCreditCardSpendDto();
      crdCreditCardSpendDto0.setExpireDate(localDate0);
      Long long0 = new Long(1052L);
      crdCreditCardSpendDto0.setCvvNo(long0);
      crdCreditCardSpendDto0.setCardNo(long0);
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigInteger bigInteger0 = BigInteger.TEN;
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0);
      crdCreditCardSpendDto0.setDescription("");
      crdCreditCardSpendDto0.setAmount(bigDecimal0);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlAreFieldsNull(crdCreditCardSpendDto0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      Long long0 = new Long((-608L));
      CrdCreditCardSpendDto crdCreditCardSpendDto0 = new CrdCreditCardSpendDto();
      crdCreditCardSpendDto0.setCvvNo(long0);
      crdCreditCardSpendDto0.setDescription("com.cbarkinozer.onlinebankingrestapi.app.gen.exceptions.GenBusinessException");
      Clock clock0 = MockClock.system(zoneOffset0);
      LocalDate localDate0 = MockLocalDate.now(clock0);
      crdCreditCardSpendDto0.setExpireDate(localDate0);
      crdCreditCardSpendDto0.setCardNo(long0);
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigInteger bigInteger0 = BigInteger.TEN;
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0);
      crdCreditCardSpendDto0.setAmount(bigDecimal0);
      crdCreditCardValidationService0.controlAreFieldsNull(crdCreditCardSpendDto0);
      assertEquals((-608L), (long)crdCreditCardSpendDto0.getCvvNo());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      Long long0 = new Long((-608L));
      CrdCreditCardSpendDto crdCreditCardSpendDto0 = new CrdCreditCardSpendDto();
      crdCreditCardSpendDto0.setCvvNo(long0);
      Clock clock0 = MockClock.system(zoneOffset0);
      LocalDate localDate0 = MockLocalDate.now(clock0);
      crdCreditCardSpendDto0.setExpireDate(localDate0);
      crdCreditCardSpendDto0.setCardNo(long0);
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigInteger bigInteger0 = BigInteger.TEN;
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0);
      crdCreditCardSpendDto0.setAmount(bigDecimal0);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlAreFieldsNull(crdCreditCardSpendDto0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      Long long0 = new Long((-608L));
      CrdCreditCardSpendDto crdCreditCardSpendDto0 = new CrdCreditCardSpendDto();
      crdCreditCardSpendDto0.setCvvNo(long0);
      Clock clock0 = MockClock.system(zoneOffset0);
      LocalDate localDate0 = MockLocalDate.now(clock0);
      crdCreditCardSpendDto0.setExpireDate(localDate0);
      crdCreditCardSpendDto0.setCardNo(long0);
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlAreFieldsNull(crdCreditCardSpendDto0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Long long0 = new Long((-608L));
      CrdCreditCardSpendDto crdCreditCardSpendDto0 = new CrdCreditCardSpendDto();
      crdCreditCardSpendDto0.setCvvNo(long0);
      crdCreditCardSpendDto0.setCardNo(long0);
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlAreFieldsNull(crdCreditCardSpendDto0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Long long0 = new Long((-608L));
      CrdCreditCardSpendDto crdCreditCardSpendDto0 = new CrdCreditCardSpendDto();
      crdCreditCardSpendDto0.setCardNo(long0);
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlAreFieldsNull(crdCreditCardSpendDto0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCardSpendDto crdCreditCardSpendDto0 = new CrdCreditCardSpendDto();
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlAreFieldsNull(crdCreditCardSpendDto0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      Long long0 = new Long(1L);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlAreFieldsNull(long0, (BigDecimal) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((double) 7);
      Long long0 = new Long(7);
      crdCreditCardValidationService0.controlAreFieldsNull(long0, bigDecimal0);
      assertEquals((byte)7, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-1));
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlAreFieldsNull((Long) null, bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BigDecimal bigDecimal0 = new BigDecimal(1559);
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlAreFieldsNull(bigDecimal0, (Integer) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((double) 7);
      Integer integer0 = new Integer(7);
      crdCreditCardValidationService0.controlAreFieldsNull(bigDecimal0, integer0);
      assertEquals((byte)7, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      Integer integer0 = new Integer((-789));
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlAreFieldsNull((BigDecimal) null, integer0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-3581L));
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.controlIsEarningNotNegative(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      crdCreditCardValidationService0.controlIsEarningNotNegative(bigDecimal0);
      assertEquals((byte)0, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      Integer integer0 = new Integer(2337);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.isCutOffDayValid(integer0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      Integer integer0 = new Integer(7);
      crdCreditCardValidationService0.isCutOffDayValid(integer0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      Integer integer0 = new Integer((-5358));
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.isCutOffDayValid(integer0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCard crdCreditCard0 = new CrdCreditCard();
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-3659L));
      crdCreditCard0.setExpireDate(localDate0);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.validateCreditCard(crdCreditCard0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCard crdCreditCard0 = new CrdCreditCard();
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      crdCreditCard0.setExpireDate(localDate0);
      crdCreditCardValidationService0.validateCreditCard(crdCreditCard0);
      assertNull(crdCreditCard0.getCardNo());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.validateCreditCard((CrdCreditCard) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      CrdCreditCard crdCreditCard0 = new CrdCreditCard();
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.validateCreditCard(crdCreditCard0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigDecimal bigDecimal0 = new BigDecimal((-2391));
      // Undeclared exception!
      try { 
        crdCreditCardValidationService0.validateCardLimit(bigDecimal0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.cbarkinozer.onlinebankingrestapi.app.crd.service.CrdCreditCardValidationService", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CrdCreditCardValidationService crdCreditCardValidationService0 = new CrdCreditCardValidationService((CrdCreditCardEntityService) null);
      BigInteger bigInteger0 = BigInteger.TEN;
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0);
      crdCreditCardValidationService0.validateCardLimit(bigDecimal0);
      assertEquals((short)10, bigDecimal0.shortValue());
  }
}
