/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 21:08:54 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.acc.enums;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cbarkinozer.onlinebankingrestapi.app.acc.enums.AccErrorMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AccErrorMessage_ESTest extends AccErrorMessage_ESTest_scaffolding {

    /**
     * Test the values() method to ensure it returns all enum constants.
     */
    @Test(timeout = 4000)
    public void testValues_ShouldReturnAllEnumConstants() throws Throwable {
        AccErrorMessage[] errorMessages = AccErrorMessage.values();
        assertEquals(6, errorMessages.length);
    }

    /**
     * Test the valueOf() method to retrieve an enum constant by name and verify its detail message.
     */
    @Test(timeout = 4000)
    public void testValueOf_WithBalanceCannotBeNegative_ShouldReturnCorrectDetailMessage() throws Throwable {
        AccErrorMessage errorMessage = AccErrorMessage.valueOf("BALANCE_CANNOT_BE_NEGATIVE");
        assertEquals("Please be sure that you entered a balance that is not negative", errorMessage.getDetailMessage());
    }

    /**
     * Test the getMessage() method of the IBAN_NO_IS_NOT_UNIQUE enum constant.
     */
    @Test(timeout = 4000)
    public void testGetMessage_IbanNoIsNotUnique_ShouldReturnCorrectMessage() throws Throwable {
        AccErrorMessage errorMessage = AccErrorMessage.IBAN_NO_IS_NOT_UNIQUE;
        String message = errorMessage.getMessage();
        assertEquals("IBAN Number Is Not Unique!", message);
    }

    /**
     * Test the getDetailMessage() method of the IBAN_NO_IS_NOT_UNIQUE enum constant.
     */
    @Test(timeout = 4000)
    public void testGetDetailMessage_IbanNoIsNotUnique_ShouldReturnCorrectDetailMessage() throws Throwable {
        AccErrorMessage errorMessage = AccErrorMessage.IBAN_NO_IS_NOT_UNIQUE;
        String detailMessage = errorMessage.getDetailMessage();
        assertEquals("Please check if the IBAN number you entered is correct.", detailMessage);
    }
}