/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 21:11:59 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.crd.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cbarkinozer.onlinebankingrestapi.app.crd.dto.CrdCreditCardDto;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.Clock;
import java.time.LocalDate;
import java.time.Period;
import java.time.chrono.IsoChronology;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CrdCreditCardDto_ESTest extends CrdCreditCardDto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      crdCreditCardDto0.setTotalLimit(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getTotalLimit();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardDto0.setTotalLimit(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getTotalLimit();
      assertEquals((byte)1, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = new BigDecimal((-1.0));
      crdCreditCardDto0.setTotalLimit(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getTotalLimit();
      assertEquals((byte) (-1), bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.valueOf((-1983L), 0);
      crdCreditCardDto0.setMinimumPaymentAmount(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getMinimumPaymentAmount();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      crdCreditCardDto0.setMinimumPaymentAmount(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getMinimumPaymentAmount();
      assertEquals((byte)0, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardDto0.setMinimumPaymentAmount(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getMinimumPaymentAmount();
      assertEquals((byte)1, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = new BigDecimal(1774.035407535);
      crdCreditCardDto0.setMinimumPaymentAmount(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getMinimumPaymentAmount();
      assertEquals((short)1774, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long(1L);
      crdCreditCardDto0.setId(long0);
      Long long1 = crdCreditCardDto0.getId();
      assertEquals(1L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-1L));
      crdCreditCardDto0.setId(long0);
      Long long1 = crdCreditCardDto0.getId();
      assertEquals((-1L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto0.setExpireDate(localDate0);
      LocalDate localDate1 = crdCreditCardDto0.getExpireDate();
      assertSame(localDate1, localDate0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto0.setDueDate(localDate0);
      LocalDate localDate1 = crdCreditCardDto0.getDueDate();
      assertSame(localDate1, localDate0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long(0L);
      crdCreditCardDto0.setCvvNo(long0);
      Long long1 = crdCreditCardDto0.getCvvNo();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long(711L);
      crdCreditCardDto0.setCvvNo(long0);
      Long long1 = crdCreditCardDto0.getCvvNo();
      assertEquals(711L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-1L));
      crdCreditCardDto0.setCvvNo(long0);
      Long long1 = crdCreditCardDto0.getCvvNo();
      assertEquals((-1L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Period period0 = Period.ofYears(3785);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      crdCreditCardDto0.setCutoffDate(localDate0);
      LocalDate localDate1 = crdCreditCardDto0.getCutoffDate();
      assertSame(localDate1, localDate0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long(0L);
      crdCreditCardDto0.setCusCustomerId(long0);
      Long long1 = crdCreditCardDto0.getCusCustomerId();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long(534L);
      crdCreditCardDto0.setCusCustomerId(long0);
      Long long1 = crdCreditCardDto0.getCusCustomerId();
      assertEquals(534L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-1707L));
      crdCreditCardDto0.setCusCustomerId(long0);
      Long long1 = crdCreditCardDto0.getCusCustomerId();
      assertEquals((-1707L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = new BigDecimal(0L);
      crdCreditCardDto0.setCurrentDebt(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getCurrentDebt();
      assertEquals((byte)0, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      crdCreditCardDto0.setCurrentDebt(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getCurrentDebt();
      assertEquals((short)10, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long(0L);
      crdCreditCardDto0.setCardNo(long0);
      Long long1 = crdCreditCardDto0.getCardNo();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long(534L);
      crdCreditCardDto0.setCardNo(long0);
      Long long1 = crdCreditCardDto0.getCardNo();
      assertEquals(534L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-2152L));
      crdCreditCardDto0.setCardNo(long0);
      Long long1 = crdCreditCardDto0.getCardNo();
      assertEquals((-2152L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      crdCreditCardDto0.setCancelDate(localDate0);
      LocalDate localDate1 = crdCreditCardDto0.getCancelDate();
      assertSame(localDate1, localDate0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      byte[] byteArray0 = new byte[6];
      BigInteger bigInteger0 = new BigInteger(byteArray0);
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0);
      crdCreditCardDto0.setAvailableCardLimit(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getAvailableCardLimit();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardDto0.setAvailableCardLimit(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getAvailableCardLimit();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = new BigDecimal((double) (-104L));
      crdCreditCardDto0.setAvailableCardLimit(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getAvailableCardLimit();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      boolean boolean0 = crdCreditCardDto0.canEqual(crdCreditCardDto0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Object object0 = new Object();
      boolean boolean0 = crdCreditCardDto0.canEqual(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = crdCreditCardDto0.getId();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = crdCreditCardDto0.getMinimumPaymentAmount();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = crdCreditCardDto0.getCusCustomerId();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = crdCreditCardDto0.getCvvNo();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = crdCreditCardDto0.getCutoffDate();
      assertNull(localDate0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = crdCreditCardDto0.getDueDate();
      assertNull(localDate0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = crdCreditCardDto0.getCancelDate();
      assertNull(localDate0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = crdCreditCardDto0.getAvailableCardLimit();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = crdCreditCardDto0.getCurrentDebt();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = crdCreditCardDto0.getTotalLimit();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = crdCreditCardDto0.getCardNo();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = crdCreditCardDto0.getExpireDate();
      assertNull(localDate0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto0.setCancelDate(localDate0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      crdCreditCardDto1.setCancelDate(localDate0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto1.setCancelDate(localDate0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto0.setCancelDate(localDate0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto0.setDueDate(localDate0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      crdCreditCardDto1.setDueDate(localDate0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto1.setDueDate(localDate0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto1.setDueDate(localDate0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto1.setCutoffDate(localDate0);
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      crdCreditCardDto0.setCutoffDate(localDate0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto0.setCutoffDate(localDate0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto1.setCutoffDate(localDate0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      crdCreditCardDto0.setMinimumPaymentAmount(bigDecimal0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      crdCreditCardDto1.setMinimumPaymentAmount(bigDecimal0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      BigDecimal bigDecimal0 = new BigDecimal(0.0);
      crdCreditCardDto0.setMinimumPaymentAmount(bigDecimal0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      crdCreditCardDto0.setCurrentDebt(bigDecimal0);
      assertFalse(crdCreditCardDto0.equals((Object)crdCreditCardDto1));
      
      crdCreditCardDto1.setCurrentDebt(bigDecimal0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertTrue(crdCreditCardDto0.equals((Object)crdCreditCardDto1));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      crdCreditCardDto1.setCurrentDebt(bigDecimal0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      crdCreditCardDto1.setCurrentDebt(bigDecimal0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardDto0.setAvailableCardLimit(bigDecimal0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      crdCreditCardDto1.setAvailableCardLimit(bigDecimal0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      crdCreditCardDto0.setAvailableCardLimit(bigDecimal0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      crdCreditCardDto1.setTotalLimit(bigDecimal0);
      crdCreditCardDto0.setTotalLimit(bigDecimal0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardDto0.setAvailableCardLimit(bigDecimal0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      crdCreditCardDto1.setTotalLimit(bigDecimal0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      crdCreditCardDto1.setTotalLimit(bigDecimal0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto1.setExpireDate(localDate0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      crdCreditCardDto1.setExpireDate(localDate0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      Long long0 = new Long((-234L));
      crdCreditCardDto0.setCvvNo(long0);
      assertFalse(crdCreditCardDto0.equals((Object)crdCreditCardDto1));
      
      crdCreditCardDto1.setCvvNo(long0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertTrue(crdCreditCardDto0.equals((Object)crdCreditCardDto1));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      Long long0 = new Long(304L);
      crdCreditCardDto1.setCvvNo(long0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      Long long0 = new Long((-234L));
      crdCreditCardDto1.setCvvNo(long0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-1534L));
      crdCreditCardDto0.setCardNo(long0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      crdCreditCardDto1.setCardNo(long0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-2119L));
      crdCreditCardDto0.setCardNo(long0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Long long0 = new Long((-2152L));
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      crdCreditCardDto0.setCusCustomerId(long0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      crdCreditCardDto1.setCusCustomerId(long0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-2306L));
      crdCreditCardDto0.setCusCustomerId(long0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      Long long0 = new Long((-1296L));
      crdCreditCardDto1.setCusCustomerId(long0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      Long long0 = new Long(494L);
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      crdCreditCardDto0.setId(long0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      crdCreditCardDto1.setId(long0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-1L));
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      crdCreditCardDto1.setId(long0);
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      Long long0 = new Long(494L);
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      crdCreditCardDto0.setId(long0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Object object0 = new Object();
      boolean boolean0 = crdCreditCardDto0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardDto0.setMinimumPaymentAmount(bigDecimal0);
      crdCreditCardDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = new BigDecimal(0L);
      crdCreditCardDto0.setCurrentDebt(bigDecimal0);
      crdCreditCardDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1L));
      crdCreditCardDto0.setExpireDate(localDate0);
      crdCreditCardDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-52L));
      crdCreditCardDto0.setCvvNo(long0);
      crdCreditCardDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-1L));
      crdCreditCardDto0.setCardNo(long0);
      crdCreditCardDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-52L));
      crdCreditCardDto0.setCusCustomerId(long0);
      crdCreditCardDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long(1L);
      crdCreditCardDto0.setId(long0);
      crdCreditCardDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto0.setCancelDate(localDate0);
      crdCreditCardDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      crdCreditCardDto0.setTotalLimit(bigDecimal0);
      crdCreditCardDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto0.setDueDate(localDate0);
      crdCreditCardDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      String string0 = crdCreditCardDto0.toString();
      assertEquals("CrdCreditCardDto(id=null, cusCustomerId=null, cardNo=null, cvvNo=null, expireDate=null, totalLimit=null, availableCardLimit=null, currentDebt=null, minimumPaymentAmount=null, cutoffDate=null, dueDate=null, cancelDate=null)", string0);
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long((-1534L));
      crdCreditCardDto0.setCardNo(long0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.valueOf((-2213L), (-1));
      crdCreditCardDto0.setCurrentDebt(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardDto0.getCurrentDebt();
      assertEquals((short) (-22130), bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto0.setCutoffDate(localDate0);
      crdCreditCardDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      Long long0 = new Long(0L);
      crdCreditCardDto0.setId(long0);
      Long long1 = crdCreditCardDto0.getId();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      crdCreditCardDto0.setMinimumPaymentAmount(bigDecimal0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      boolean boolean0 = crdCreditCardDto0.equals(crdCreditCardDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      LocalDate localDate0 = MockLocalDate.now();
      crdCreditCardDto0.setExpireDate(localDate0);
      CrdCreditCardDto crdCreditCardDto1 = new CrdCreditCardDto();
      assertFalse(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      
      crdCreditCardDto1.setExpireDate(localDate0);
      boolean boolean0 = crdCreditCardDto1.equals(crdCreditCardDto0);
      assertTrue(crdCreditCardDto1.equals((Object)crdCreditCardDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test92()  throws Throwable  {
      CrdCreditCardDto crdCreditCardDto0 = new CrdCreditCardDto();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardDto0.setAvailableCardLimit(bigDecimal0);
      crdCreditCardDto0.hashCode();
  }
}
