/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 21:10:54 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.crd.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cbarkinozer.onlinebankingrestapi.app.crd.dto.CrdCreditCardActivityDto;
import com.cbarkinozer.onlinebankingrestapi.app.crd.enums.CrdCreditCardActivityType;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CrdCreditCardActivityDto_ESTest extends CrdCreditCardActivityDto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      crdCreditCardActivityDto0.setTransactionDate(localDateTime0);
      LocalDateTime localDateTime1 = crdCreditCardActivityDto0.getTransactionDate();
      assertSame(localDateTime1, localDateTime0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long(0L);
      crdCreditCardActivityDto0.setId(long0);
      Long long1 = crdCreditCardActivityDto0.getId();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long(2135L);
      crdCreditCardActivityDto0.setId(long0);
      Long long1 = crdCreditCardActivityDto0.getId();
      assertEquals(2135L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long((-801L));
      crdCreditCardActivityDto0.setId(long0);
      Long long1 = crdCreditCardActivityDto0.getId();
      assertEquals((-801L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      crdCreditCardActivityDto0.setDescription("X\"'zbZEO");
      String string0 = crdCreditCardActivityDto0.getDescription();
      assertEquals("X\"'zbZEO", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      crdCreditCardActivityDto0.setDescription("");
      String string0 = crdCreditCardActivityDto0.getDescription();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long(0L);
      crdCreditCardActivityDto0.setCrdCreditCardId(long0);
      Long long1 = crdCreditCardActivityDto0.getCrdCreditCardId();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long(1L);
      crdCreditCardActivityDto0.setCrdCreditCardId(long0);
      Long long1 = crdCreditCardActivityDto0.getCrdCreditCardId();
      assertEquals(1L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long((-1487));
      crdCreditCardActivityDto0.setCrdCreditCardId(long0);
      Long long1 = crdCreditCardActivityDto0.getCrdCreditCardId();
      assertEquals((-1487L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityType crdCreditCardActivityType0 = CrdCreditCardActivityType.PAYMENT;
      crdCreditCardActivityDto0.setCardActivityType(crdCreditCardActivityType0);
      CrdCreditCardActivityType crdCreditCardActivityType1 = crdCreditCardActivityDto0.getCardActivityType();
      assertSame(crdCreditCardActivityType1, crdCreditCardActivityType0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      BigDecimal bigDecimal0 = new BigDecimal(0.0);
      crdCreditCardActivityDto0.setAmount(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardActivityDto0.getAmount();
      assertEquals((short)0, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardActivityDto0.setAmount(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardActivityDto0.getAmount();
      assertEquals((byte)1, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      BigDecimal bigDecimal0 = new BigDecimal((-91));
      crdCreditCardActivityDto0.setAmount(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardActivityDto0.getAmount();
      assertSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      boolean boolean0 = crdCreditCardActivityDto0.canEqual(crdCreditCardActivityDto0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      boolean boolean0 = crdCreditCardActivityDto0.canEqual((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      String string0 = crdCreditCardActivityDto0.getDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      BigDecimal bigDecimal0 = crdCreditCardActivityDto0.getAmount();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      crdCreditCardActivityDto0.getCardActivityType();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = crdCreditCardActivityDto0.getCrdCreditCardId();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      LocalDateTime localDateTime0 = crdCreditCardActivityDto0.getTransactionDate();
      assertNull(localDateTime0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = crdCreditCardActivityDto0.getId();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityType crdCreditCardActivityType0 = CrdCreditCardActivityType.SPEND;
      crdCreditCardActivityDto0.setCardActivityType(crdCreditCardActivityType0);
      assertFalse(crdCreditCardActivityDto0.equals((Object)crdCreditCardActivityDto1));
      
      crdCreditCardActivityDto1.setCardActivityType(crdCreditCardActivityType0);
      boolean boolean0 = crdCreditCardActivityDto1.equals(crdCreditCardActivityDto0);
      assertTrue(crdCreditCardActivityDto0.equals((Object)crdCreditCardActivityDto1));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityType crdCreditCardActivityType0 = CrdCreditCardActivityType.PAYMENT;
      crdCreditCardActivityDto0.setCardActivityType(crdCreditCardActivityType0);
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      boolean boolean0 = crdCreditCardActivityDto1.equals(crdCreditCardActivityDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      assertTrue(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      
      CrdCreditCardActivityType crdCreditCardActivityType0 = CrdCreditCardActivityType.SPEND;
      crdCreditCardActivityDto1.setCardActivityType(crdCreditCardActivityType0);
      boolean boolean0 = crdCreditCardActivityDto1.equals(crdCreditCardActivityDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      crdCreditCardActivityDto0.setDescription("$VALUES");
      assertFalse(crdCreditCardActivityDto0.equals((Object)crdCreditCardActivityDto1));
      
      crdCreditCardActivityDto1.setDescription("$VALUES");
      boolean boolean0 = crdCreditCardActivityDto1.equals(crdCreditCardActivityDto0);
      assertTrue(crdCreditCardActivityDto0.equals((Object)crdCreditCardActivityDto1));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      assertTrue(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      
      crdCreditCardActivityDto1.setDescription("");
      boolean boolean0 = crdCreditCardActivityDto0.equals(crdCreditCardActivityDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      crdCreditCardActivityDto0.setDescription("");
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      boolean boolean0 = crdCreditCardActivityDto0.equals(crdCreditCardActivityDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      crdCreditCardActivityDto0.setTransactionDate(localDateTime0);
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      assertFalse(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      
      crdCreditCardActivityDto1.setTransactionDate(localDateTime0);
      boolean boolean0 = crdCreditCardActivityDto0.equals(crdCreditCardActivityDto1);
      assertTrue(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      ZoneOffset zoneOffset0 = ZoneOffset.UTC;
      LocalDateTime localDateTime0 = MockLocalDateTime.ofEpochSecond((-1L), 24, zoneOffset0);
      crdCreditCardActivityDto0.setTransactionDate(localDateTime0);
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      boolean boolean0 = crdCreditCardActivityDto1.equals(crdCreditCardActivityDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      assertTrue(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      crdCreditCardActivityDto1.setTransactionDate(localDateTime0);
      boolean boolean0 = crdCreditCardActivityDto1.equals(crdCreditCardActivityDto0);
      assertFalse(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      BigDecimal bigDecimal0 = new BigDecimal(0);
      crdCreditCardActivityDto0.setAmount(bigDecimal0);
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      assertFalse(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      
      crdCreditCardActivityDto1.setAmount(bigDecimal0);
      boolean boolean0 = crdCreditCardActivityDto0.equals(crdCreditCardActivityDto1);
      assertTrue(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      assertTrue(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardActivityDto1.setAmount(bigDecimal0);
      boolean boolean0 = crdCreditCardActivityDto1.equals(crdCreditCardActivityDto0);
      assertFalse(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      assertTrue(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      
      Long long0 = new Long(0L);
      crdCreditCardActivityDto1.setCrdCreditCardId(long0);
      boolean boolean0 = crdCreditCardActivityDto0.equals(crdCreditCardActivityDto1);
      assertFalse(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      assertTrue(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      
      Long long0 = new Long(0L);
      crdCreditCardActivityDto1.setCrdCreditCardId(long0);
      boolean boolean0 = crdCreditCardActivityDto1.equals(crdCreditCardActivityDto0);
      assertFalse(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long(0L);
      crdCreditCardActivityDto0.setId(long0);
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      assertFalse(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      
      crdCreditCardActivityDto1.setId(long0);
      boolean boolean0 = crdCreditCardActivityDto0.equals(crdCreditCardActivityDto1);
      assertTrue(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long(0L);
      crdCreditCardActivityDto0.setId(long0);
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      boolean boolean0 = crdCreditCardActivityDto1.equals(crdCreditCardActivityDto0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long(0L);
      crdCreditCardActivityDto0.setId(long0);
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      boolean boolean0 = crdCreditCardActivityDto0.equals(crdCreditCardActivityDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Object object0 = new Object();
      boolean boolean0 = crdCreditCardActivityDto0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      boolean boolean0 = crdCreditCardActivityDto0.equals(crdCreditCardActivityDto0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      BigInteger bigInteger0 = BigInteger.TWO;
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0);
      crdCreditCardActivityDto0.setAmount(bigDecimal0);
      crdCreditCardActivityDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long(616L);
      crdCreditCardActivityDto0.setCrdCreditCardId(long0);
      crdCreditCardActivityDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardActivityDto0.setAmount(bigDecimal0);
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      boolean boolean0 = crdCreditCardActivityDto1.equals(crdCreditCardActivityDto0);
      assertFalse(boolean0);
      assertFalse(crdCreditCardActivityDto0.equals((Object)crdCreditCardActivityDto1));
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      CrdCreditCardActivityType crdCreditCardActivityType0 = CrdCreditCardActivityType.SPEND;
      crdCreditCardActivityDto0.setCardActivityType(crdCreditCardActivityType0);
      crdCreditCardActivityDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      crdCreditCardActivityDto0.setDescription("");
      crdCreditCardActivityDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long(0L);
      crdCreditCardActivityDto0.setCrdCreditCardId(long0);
      CrdCreditCardActivityDto crdCreditCardActivityDto1 = new CrdCreditCardActivityDto();
      assertFalse(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      
      crdCreditCardActivityDto1.setCrdCreditCardId(long0);
      boolean boolean0 = crdCreditCardActivityDto0.equals(crdCreditCardActivityDto1);
      assertTrue(crdCreditCardActivityDto1.equals((Object)crdCreditCardActivityDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      Long long0 = new Long(0L);
      crdCreditCardActivityDto0.setId(long0);
      crdCreditCardActivityDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      String string0 = crdCreditCardActivityDto0.toString();
      assertEquals("CrdCreditCardActivityDto(id=null, crdCreditCardId=null, amount=null, transactionDate=null, description=null, cardActivityType=null)", string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      CrdCreditCardActivityDto crdCreditCardActivityDto0 = new CrdCreditCardActivityDto();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      crdCreditCardActivityDto0.setTransactionDate(localDateTime0);
      crdCreditCardActivityDto0.hashCode();
  }
}
