/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 21:12:12 GMT 2025
 */

package com.cbarkinozer.onlinebankingrestapi.app.crd.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cbarkinozer.onlinebankingrestapi.app.crd.dto.CrdCreditCardSaveDto;
import java.math.BigDecimal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CrdCreditCardSaveDto_ESTest extends CrdCreditCardSaveDto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      BigDecimal bigDecimal0 = BigDecimal.ZERO;
      crdCreditCardSaveDto0.setEarning(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardSaveDto0.getEarning();
      assertEquals((short)0, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      BigDecimal bigDecimal0 = new BigDecimal((-3205.037978423279));
      crdCreditCardSaveDto0.setEarning(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardSaveDto0.getEarning();
      assertEquals((byte)123, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      BigDecimal bigDecimal0 = new BigDecimal(762);
      crdCreditCardSaveDto0.setEarning(bigDecimal0);
      BigDecimal bigDecimal1 = crdCreditCardSaveDto0.getEarning();
      assertEquals((byte) (-6), bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      Integer integer0 = new Integer(0);
      crdCreditCardSaveDto0.setCutOffDay(integer0);
      Integer integer1 = crdCreditCardSaveDto0.getCutOffDay();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      Integer integer0 = new Integer(615);
      crdCreditCardSaveDto0.setCutOffDay(integer0);
      Integer integer1 = crdCreditCardSaveDto0.getCutOffDay();
      assertEquals(615, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      Integer integer0 = new Integer((-1970));
      crdCreditCardSaveDto0.setCutOffDay(integer0);
      Integer integer1 = crdCreditCardSaveDto0.getCutOffDay();
      assertEquals((-1970), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      boolean boolean0 = crdCreditCardSaveDto0.canEqual(crdCreditCardSaveDto0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      Object object0 = new Object();
      boolean boolean0 = crdCreditCardSaveDto0.canEqual(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      BigDecimal bigDecimal0 = crdCreditCardSaveDto0.getEarning();
      assertNull(bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      Integer integer0 = crdCreditCardSaveDto0.getCutOffDay();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      CrdCreditCardSaveDto crdCreditCardSaveDto1 = new CrdCreditCardSaveDto();
      char[] charArray0 = new char[1];
      charArray0[0] = '5';
      BigDecimal bigDecimal0 = new BigDecimal(charArray0);
      crdCreditCardSaveDto0.setEarning(bigDecimal0);
      assertFalse(crdCreditCardSaveDto0.equals((Object)crdCreditCardSaveDto1));
      
      crdCreditCardSaveDto1.setEarning(bigDecimal0);
      boolean boolean0 = crdCreditCardSaveDto0.equals(crdCreditCardSaveDto1);
      assertTrue(crdCreditCardSaveDto1.equals((Object)crdCreditCardSaveDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      CrdCreditCardSaveDto crdCreditCardSaveDto1 = new CrdCreditCardSaveDto();
      assertTrue(crdCreditCardSaveDto1.equals((Object)crdCreditCardSaveDto0));
      
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardSaveDto1.setEarning(bigDecimal0);
      boolean boolean0 = crdCreditCardSaveDto0.equals(crdCreditCardSaveDto1);
      assertFalse(crdCreditCardSaveDto1.equals((Object)crdCreditCardSaveDto0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      CrdCreditCardSaveDto crdCreditCardSaveDto1 = new CrdCreditCardSaveDto();
      assertTrue(crdCreditCardSaveDto1.equals((Object)crdCreditCardSaveDto0));
      
      char[] charArray0 = new char[1];
      charArray0[0] = '5';
      BigDecimal bigDecimal0 = new BigDecimal(charArray0);
      crdCreditCardSaveDto0.setEarning(bigDecimal0);
      boolean boolean0 = crdCreditCardSaveDto0.equals(crdCreditCardSaveDto1);
      assertFalse(crdCreditCardSaveDto1.equals((Object)crdCreditCardSaveDto0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      Integer integer0 = new Integer(0);
      crdCreditCardSaveDto0.setCutOffDay(integer0);
      CrdCreditCardSaveDto crdCreditCardSaveDto1 = new CrdCreditCardSaveDto();
      assertFalse(crdCreditCardSaveDto1.equals((Object)crdCreditCardSaveDto0));
      
      crdCreditCardSaveDto1.setCutOffDay(integer0);
      boolean boolean0 = crdCreditCardSaveDto0.equals(crdCreditCardSaveDto1);
      assertTrue(crdCreditCardSaveDto1.equals((Object)crdCreditCardSaveDto0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      CrdCreditCardSaveDto crdCreditCardSaveDto1 = new CrdCreditCardSaveDto();
      assertTrue(crdCreditCardSaveDto1.equals((Object)crdCreditCardSaveDto0));
      
      Integer integer0 = new Integer((-2146));
      crdCreditCardSaveDto1.setCutOffDay(integer0);
      boolean boolean0 = crdCreditCardSaveDto0.equals(crdCreditCardSaveDto1);
      assertFalse(crdCreditCardSaveDto1.equals((Object)crdCreditCardSaveDto0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      Integer integer0 = new Integer(1);
      crdCreditCardSaveDto0.setCutOffDay(integer0);
      CrdCreditCardSaveDto crdCreditCardSaveDto1 = new CrdCreditCardSaveDto();
      boolean boolean0 = crdCreditCardSaveDto0.equals(crdCreditCardSaveDto1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      Object object0 = new Object();
      boolean boolean0 = crdCreditCardSaveDto0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      boolean boolean0 = crdCreditCardSaveDto0.equals(crdCreditCardSaveDto0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      crdCreditCardSaveDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      Integer integer0 = new Integer((-671));
      crdCreditCardSaveDto0.setCutOffDay(integer0);
      crdCreditCardSaveDto0.hashCode();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      String string0 = crdCreditCardSaveDto0.toString();
      assertEquals("CrdCreditCardSaveDto(earning=null, cutOffDay=null)", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CrdCreditCardSaveDto crdCreditCardSaveDto0 = new CrdCreditCardSaveDto();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      crdCreditCardSaveDto0.setEarning(bigDecimal0);
      crdCreditCardSaveDto0.hashCode();
  }
}
